controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

generate_pdf:
    path: /generate-pdf
    controller: App\Controller\PdfController::generatePdf
